const tg=window.Telegram?.WebApp;if(tg){tg.ready();tg.expand()}const initData=tg?.initData||'';const headers={'X-Telegram-Init-Data':initData};let activeWorkoutId=null;let knownExercises=[];let progressData=null;let progressMetric='weight';
function set(id,v){document.getElementById(id).textContent=v}
function show(name){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(name).classList.add('active');if(name==='food')loadFood();if(name==='workouts')loadWorkouts();if(name==='weights')loadWeights();if(name==='progress')loadExerciseChoices()}
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{...headers,'Content-Type':'application/json',...(opts.headers||{})}});if(!r.ok)throw Error(await r.text());return r.json()}
async function load(){if(!initData){set('error','Открой приложение внутри Telegram.');return}try{const[me,d]=await Promise.all([api('/api/me'),api('/api/dashboard')]);set('greeting',`Привет, ${me.first_name||me.username||'спортсмен'} 👋`);set('calories',Math.round(d.calories.current));set('calorieTarget',`/ ${Math.round(d.calories.target||0)} ккал`);set('protein',`${Math.round(d.protein.current)} / ${Math.round(d.protein.target||0)} г`);set('fat',`${Math.round(d.fat.current)} / ${Math.round(d.fat.target||0)} г`);set('carbs',`${Math.round(d.carbohydrates.current)} / ${Math.round(d.carbohydrates.target||0)} г`);set('weight',d.weight_kg==null?'—':`${d.weight_kg} кг`);set('workouts',d.workouts_last_7_days);const t=d.calories.target||0;document.getElementById('calorieFill').style.width=`${Math.min(100,t?d.calories.current/t*100:0)}%`}catch(e){set('error','Не удалось загрузить данные.')}}
async function loadFood(){try{const d=await api('/api/food/today'),el=document.getElementById('foodList');if(!d.items.length){el.textContent='Сегодня ещё ничего не записано.';return}el.innerHTML=d.items.map(x=>`<div class="row"><span>${x.product_name}<br><small>${x.meal}, ${x.grams} г</small></span><strong>${Math.round(x.calories)} ккал</strong></div>`).join('')}catch(e){set('foodList','Не удалось загрузить питание.')}}
async function loadWorkouts(){try{const d=await api('/api/workouts'),el=document.getElementById('workoutList');if(!d.items.length){el.textContent='Тренировок пока нет.';return}el.className='card';el.innerHTML=d.items.map(x=>`<div class="row"><button onclick="openWorkout(${x.id})">${x.name}</button><span>${new Date(x.performed_at).toLocaleDateString('ru-RU')}</span></div>`).join('')}catch(e){set('workoutList','Не удалось загрузить тренировки.')}}
async function addWorkout(){const msg=document.getElementById('workoutMsg');try{const x=await api('/api/workouts',{method:'POST',body:JSON.stringify({name:workoutName.value,notes:workoutNotes.value||null})});activeWorkoutId=x.id;msg.className='ok';msg.textContent='Тренировка создана ✓';workoutName.value='';workoutNotes.value='';await loadWorkouts();await openWorkout(activeWorkoutId)}catch(e){msg.className='error';msg.textContent='Не удалось создать тренировку.'}}
async function openWorkout(id){activeWorkoutId=id;const d=await api(`/api/workouts/${id}`),el=document.getElementById('activeWorkout');el.innerHTML=`<div class="card"><h3>${d.workout.name}</h3><div id="exerciseList">${d.exercises.map(renderExercise).join('')||'<div class="empty">Упражнений пока нет.</div>'}</div><div class="form" style="margin-top:12px"><input id="exerciseName" placeholder="Новое упражнение"><button onclick="addExercise()">Добавить упражнение</button></div><div class="form done"><input id="duration" type="number" min="1" placeholder="Длительность, минут"><input id="burned" type="number" min="0" placeholder="Потрачено ккал"><button onclick="completeWorkout()">Завершить тренировку</button></div></div>`}
function renderExercise(x){const sets=x.sets||[];return `<div class="exercise"><strong>${x.exercise.name}</strong><div>${sets.map(s=>`<div class="row"><span>Подход ${s.set_number}: ${s.weight_kg} кг × ${s.reps}${s.rpe==null?'':` · RPE ${s.rpe}`}</span><button class="danger" onclick="deleteSet(${s.id})">×</button></div>`).join('')||'<div class="small">Подходов пока нет.</div>'}</div><div class="setrow"><input id="w-${x.exercise.id}" type="number" min="0" step="0.5" placeholder="кг"><input id="r-${x.exercise.id}" type="number" min="1" placeholder="повт."><input id="rpe-${x.exercise.id}" type="number" min="1" max="10" step="0.5" placeholder="RPE"><button onclick="addSet(${x.exercise.id})">+</button></div></div>`}
async function addExercise(){const name=document.getElementById('exerciseName').value.trim();if(!name||!activeWorkoutId)return;await api('/api/workouts/exercises',{method:'POST',body:JSON.stringify({workout_id:activeWorkoutId,name,position:document.querySelectorAll('.exercise').length+1})});document.getElementById('exerciseName').value='';await openWorkout(activeWorkoutId)}
async function addSet(id){const w=document.getElementById(`w-${id}`),r=document.getElementById(`r-${id}`),rpe=document.getElementById(`rpe-${id}`);const d=await api(`/api/workouts/${activeWorkoutId}`),ex=d.exercises.find(x=>x.exercise.id===id);if(!w.value||!r.value)return;await api('/api/workouts/sets',{method:'POST',body:JSON.stringify({exercise_id:id,set_number:(ex.sets||[]).length+1,weight_kg:+w.value,reps:+r.value,rpe:rpe.value?+rpe.value:null})});await openWorkout(activeWorkoutId)}
async function deleteSet(id){if(!confirm('Удалить подход?'))return;await api(`/api/workouts/sets/${id}`,{method:'DELETE'});await openWorkout(activeWorkoutId)}
async function completeWorkout(){const duration=document.getElementById('duration').value,burned=document.getElementById('burned').value;try{await api(`/api/workouts/${activeWorkoutId}/complete`,{method:'POST',body:JSON.stringify({duration_minutes:duration?+duration:null,calories_burned:burned?+burned:null})});activeWorkoutId=null;document.getElementById('activeWorkout').innerHTML='';await loadWorkouts();await load()}catch(e){set('error','Не удалось завершить тренировку.')}}
async function loadWeights(){try{const d=await api('/api/weights'),el=document.getElementById('weightList');if(!d.items.length){el.textContent='История веса пуста.';return}el.innerHTML=d.items.map(x=>`<div class="row"><span>${new Date(x.measured_at).toLocaleDateString('ru-RU')}</span><strong>${x.weight_kg} кг</strong></div>`).join('')}catch(e){set('weightList','Не удалось загрузить вес.')}}
async function addWeight(){const msg=document.getElementById('weightMsg');try{await api('/api/weights',{method:'POST',body:JSON.stringify({weight_kg:+weightInput.value})});msg.className='ok';msg.textContent='Вес записан ✓';weightInput.value='';await loadWeights();await load()}catch(e){msg.className='error';msg.textContent='Не удалось записать вес.')}}
async function loadExerciseChoices(){const choices=document.getElementById('exerciseChoices');try{const d=await api('/api/workouts');const names=new Map();for(const workout of d.items){try{const detail=await api(`/api/workouts/${workout.id}`);for(const item of detail.exercises||[]){const name=item.exercise.name.trim();if(name)names.set(name.toLowerCase(),name)}}catch(e){}}knownExercises=[...names.values()].sort((a,b)=>a.localeCompare(b,'ru'));choices.innerHTML=knownExercises.length?knownExercises.map(name=>`<button class="exercise-chip" onclick="selectExercise(${JSON.stringify(name)})">${name}</button>`).join(''):'<span class="small">Пока нет упражнений.</span>';document.getElementById('exerciseDatalist').innerHTML=knownExercises.map(name=>`<option value="${name.replace(/"/g,'&quot;')}">`).join('')}catch(e){choices.innerHTML='<span class="error">Не удалось загрузить упражнения.</span>'}}
function selectExercise(name){document.getElementById('progressExercise').value=name;loadProgress()}
async function loadProgress(){const name=document.getElementById('progressExercise').value.trim();if(!name)return;const el=document.getElementById('progressResult');el.innerHTML='<div class="card">Загрузка…</div>';try{progressData=await api(`/api/workouts/progress/${encodeURIComponent(name)}`);renderProgress()}catch(e){el.innerHTML='<div class="card error">Не удалось загрузить прогресс. Проверь название упражнения.</div>'}}
function metricValue(s){if(progressMetric==='weight')return Number(s.max_weight)||0;if(progressMetric==='volume')return Number(s.volume)||0;return Number(s.estimated_1rm)||0}
function renderProgress(){const d=progressData,sessions=d.sessions||[],el=document.getElementById('progressResult'),max=Math.max(...sessions.map(metricValue),1),metricLabel=progressMetric==='weight'?'Макс. вес, кг':progressMetric==='volume'?'Объём, кг':'Расчётный 1RM, кг';el.innerHTML=`<div class="card"><h3>${d.exercise}</h3><div class="metrics"><div class="metric"><strong>${d.best_weight??'—'}</strong><span>Лучший вес, кг</span></div><div class="metric"><strong>${d.best_volume??'—'}</strong><span>Лучший объём</span></div><div class="metric"><strong>${d.estimated_1rm??'—'}</strong><span>Расчётный 1RM</span></div></div><div class="tabs"><button class="${progressMetric==='weight'?'active':''}" onclick="setMetric('weight')">Вес</button><button class="${progressMetric==='volume'?'active':''}" onclick="setMetric('volume')">Объём</button><button class="${progressMetric==='1rm'?'active':''}" onclick="setMetric('1rm')">1RM</button></div><div class="muted">${metricLabel}</div><div class="chart">${sessions.slice(-12).map(s=>`<div class="baritem"><div class="barvalue" style="height:${Math.max(3,metricValue(s)/max*125)}px"></div><span class="barlabel">${metricValue(s)}</span><span class="barlabel">${new Date(s.performed_at).toLocaleDateString('ru-RU',{day:'2-digit',month:'2-digit'})}</span></div>`).join('')||'<span class="small">Недостаточно данных.</span>'}</div><h4>Тренировки</h4>${sessions.slice().reverse().map(s=>`<div class="row"><span>${new Date(s.performed_at).toLocaleDateString('ru-RU')}<br><small>${s.sets_count} подходов</small></span><strong>${s.max_weight} кг · ${s.volume} кг</strong></div>`).join('')}</div>`}
function setMetric(metric){progressMetric=metric;renderProgress()}
load();